version: "3.7" #menjelaskan versi dari skript docker compose

services:
  #menjelaskan service apa saja yang mau dibuat pada docker
  item-app:
    #menjelaskan nama service yang mau dibuat (container/service 1)
    image: item-app #menjelaskan bahwa akan dibuatkan image tersebut pada service 1
    ports:
      #menjelaskan container/service 1 akan berjalan di port berapa
      - 80 #menjelaskan container/service 1 akan berjalan di port 80
    working_dir: /app #menjelaskan working directory path nya berada pada /app
    restart: always #menjelakan bahwa container/service ini selalu restart ketika berhenti
    volumes:
      #menjelaskan menggunakan volume app-db yang di simpan pada path ./:/app
      - ./:/app

  item-db:
    #menjelaskan nama service yang mau dibuat (container/service 2)
    image: mongo:3 #menjelaskan akan dibuatkan image tersebut pada service 2
    volumes:
      #menjelaskan menggunakan volume app-db yang di simpan pada path /data/db
      - app-db:/data/db
    restart: always #menjelakan bahwa container/service ini selalu restart ketika berhenti
    environment:
      MONGO_INITDB_ROOT_USERNAME: dicoding #menjelaskan confogurasi env untuk username db
      MONGO_INITDB_ROOT_PASSWORD: dicoding123 #menjelaskan confogurasi env untuk password db

volumes:
  #menjelaskan pembuatan volume
  app-db: #menjelaskan pembuatan volume bernama app-db
