version: "3.7" #menjelaskan versi dari skript docker compose

services:
  #menjelaskan service apa saja yang mau dibuat pada docker
  item-app:
    #menjelaskan nama service yang mau dibuat (container/service 1)
    image: rafiannas/item-app:v1 #menjelaskan bahwa akan dibuatkan image tersebut pada service 1
    ports:
      #menjelaskan container/service 1 akan berjalan di port berapa
      - 80:8080 #menjelaskan container/service 1 akan berjalan di port 80 pada host, dan port 8080 di container
    restart: always #menjelakan bahwa container/service ini selalu restart ketika berhenti
    depends_on:
      - item-db

  item-db:
    #menjelaskan nama service yang mau dibuat (container/service 2)
    image: mongo:3 #menjelaskan akan dibuatkan image tersebut pada service 2
    volumes:
      #menjelaskan menggunakan volume app-db yang di simpan pada path /data/db
      - app-db:/data/db
    restart: always #menjelakan bahwa container/service ini selalu restart ketika berhenti

volumes:
  #menjelaskan pembuatan volume
  app-db: #menjelaskan pembuatan volume bernama app-db
